[app]
name = "13cc_manager"
version = "0.1.0"
description = "13cc Manager"
authors = ["@dicapisar"]

[server]
port = "8080"
case_sensitive = true
enable_print_routes = true

[database]
host = "localhost"
port = 543
user = "postgres"
password = "password"
name = "13cc_manager"

